### ISSUE TITLE
Also bench with gdc

### ISSUE THREAD

**Issue by Bobo1239** [Bobo1239/meetup_benchmark#1]
(failed to install gdc due to disabled pgp key issues)

**Comment by lindt** [comment]
gdc is too outdated right now.....will need to wait one month until dconf :)

**Comment by Bobo1239** [comment]
Just a reminder for myself: GDC has been [upstreamed to GCC](https://github.com/gcc-mirror/gcc/commit/03385ed3d679cd8125f282697a1c7cf46f8361cc) so hopefully I can close this issue after the next GCC release.

**Comment by Bobo1239** [comment]
`gdc` is available in the Arch package repository nowadays. Finally fixed.
